package 异常;

import java.io.IOException;

public class TwoException1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		try
		{
			if(true)
			{
				throw new RuntimeException("asdas"); //不会报错，因为RuntimeException为非检查异常
				throw new Exception("asdas");//会报错,因为其他Exception子类都是检查异常
				throw new IOException("asdas");//会报错,因为其他Exception子类都是检查异常
			}
		}
		catch(IOException ex)
		{
			System.out.println("IOException");
		}
	}

}
